### ISSUE TITLE
Publish to npm 

### ISSUE THREAD

**Issue by michaelBenin** [lukasolson/backbone-super#28]
It would be great if this library was on npm. 

Thank you!

**Comment by michaelBenin** [comment]
Looks like the namespace is available: https://www.npmjs.com/package/backbone-super

**Comment by michaelBenin** [comment]
If you want, add me as a contributor and I can publish this. 

Feel free to reach out if you have any questions.

**Comment by lukasolson** [comment]
Thanks! I would appreciate that. I've added you.

**Comment by michaelBenin** [comment]
This has been tested with browserify, working well installing from github. All we need now is the tag in github and then we'll publish to npm.

**Comment by michaelBenin** [comment]
Published: https://www.npmjs.com/package/backbone-super
