### ISSUE TITLE
problems using it with browserify

### ISSUE THREAD

**Issue by rachel-carvalho** [lukasolson/backbone-super#39]
I'm trying to use this lib with the recently added npm package on browserify, but I'm having a couple of problems:

- `require('backbone-super')` throws an error `Cannot find module 'underscore'`, there's a `require('underscore')` in backbone-super.js, but it doesn't declare it as a dependency in the package.json, so unless your project depends directly on underscore, it's not going to work.

- even after underscore is installed, `_super` is not available inside backbone classes:

```javascript
'use strict';

var Backbone = require('backbone');
Backbone.$ = require('jquery');
require('backbone-super');

module.exports = Backbone.View.extend({
  initialize: function(params) {
    // this is undefined
    console.log('this._super ', this._super);
  }
});
```

As I was looking at the code, I see it doesn't expose the newly modified Backbone, so there's no way the `_super` method will be available for use.

So I propose that backbone-super exports a method called setup, which will receive Backbone and Underscore as parameters and modifies those instances. I'm working on those changes and will do a pull request soon.

Thanks for the great lib!

**Comment by rachel-carvalho** [comment]
I've just checked your tests and I see that if I do `require('backbone-super')` before requiring backbone, it works.

I still think it would be more interesting to reuse the Backbone instance explicitly, so I'll still propose the change.

Also it solves the first issue, and enables developers to use lodash instead of underscore.

**Comment by michaelBenin** [comment]
Can you update your code to be this:

```javascript
'use strict';

var Backbone = require('backbone');
Backbone.$ = require('jquery');
Backbone._ = require('underscore');
// Also this can be 
// Backbone._ = require('lodash');
require('backbone-super');

module.exports = Backbone.View.extend({
  initialize: function(params) {
    // this is undefined
    console.log('this._super ', this._super);
  }
});
```

**Comment by jifeon** [comment]
maybe backbone-super should just provide modified Backbone? Than you will be able to write like this:
```js
var Backbone = require('backbone-super');
```
It's not far from reality because backbone-super does not provide anything by itself, it just replace the `extend` method of Backbone so you can use either backbone or replaced backbone. And it would be very strange and ambiguous if `require('backbone')` will provide replaced version. And writing `require('backbone-super')` will clearly indicate version of backbone you are using

**Comment by michaelBenin** [comment]
@jifeon could you open an issue for discussion about making backbone-super export a modified backbone. Personally I would prefer requiring it once in my entry point with browserify but I could understand why some people would want it. Let's discuss further there. 

@rachel-carvalho would you mind making a PR to this project updating the documentation for commonjs for issue #34? Also if your updated code works with browserify could you close this issue? I've been using this project with browserify with no problems, we're aware there needs to be a documentation update.

We're aware there's some cleanup for commonjs.

**Comment by rachel-carvalho** [comment]
@jifeon One problem I see with this is that it would be a bit weird to combine with other Backbone extension libraries (I have a project that's not yet using Browserify, where I use backbone-hotkeys, which replaces Backbone.View and backbone-paginator, which adds a new type of Collection to Backbone).

@michaelBenin Thanks, this does work. But I think it's a bit flimsy as a method of altering Backbone, as it relies on node/browserify cache of require.

However, this is just a matter of style and the change I was proposing would break previous compatibility, so I'll just close this issue. Thank you!

**Comment by rachel-carvalho** [comment]
@michaelBenin Just an update, while your example works for using underscore, it still doesn't work with lodash, because the code explicitly requires underscore. Maybe it could just use `Backbone._`, instead of explicitly requiring it.

**Comment by michaelBenin** [comment]
That would make sense, could you create a new issue for this? I've only used this library with underscore, thanks for catching this.

**Comment by rachel-carvalho** [comment]
@michaelBenin I don't use it either, but I searched around a bit and I saw that Backbone itself also requires underscore, and that the solution is actually to alias lodash as underscore, as shown in this [gist](https://gist.github.com/knpsck/a7c2ead6120c7dca152c). So this is not actually an issue.
